### ISSUE TITLE
Creating a cert does not work

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_web#1253]
**Describe the bug**
when creating a certificate on the web ui, i encounter a server error

**To Reproduce**
create a certificate

**Screenshots**
```
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]05:34:12.702 [info] pid=<0.3346.0> mfa=NervesHubWeb.Plugs.Logger.call/2 request_id=F7-cfv9Rr5rUO1UAAAlR duration=13 method=POST path=/org/connorrigby/settings/certificates status=500 remote_ip=172.16.1.178
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]05:34:12.703 [error] pid=<0.3346.0> mfa=:gen_server.error_info/8 request_id=F7-cfv9Rr5rUO1UAAAlR GenServer #PID<0.3346.0> terminating
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]** (ArgumentError) expected argument to be a literal atom, literal keyword or a :Extension record, got runtime: nil
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]    (elixir 1.16.0) lib/record.ex:514: Record.__keyword__/3
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]    (nerves_hub 0.1.0) lib/nerves_hub/certificate.ex:21: NervesHub.Certificate.get_aki/1
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]    (nerves_hub 0.1.0) lib/nerves_hub_web/controllers/org_certificate_controller.ex:93: NervesHubWeb.OrgCertificateController.create/2
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]    (nerves_hub 0.1.0) lib/nerves_hub_web/controllers/org_certificate_controller.ex:1: NervesHubWeb.OrgCertificateController.action/2
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]    (nerves_hub 0.1.0) lib/nerves_hub_web/controllers/org_certificate_controller.ex:1: NervesHubWeb.OrgCertificateController.phoenix_controller_pipeline/2
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]    (phoenix 1.7.10) lib/phoenix/router.ex:432: Phoenix.Router.__call__/5
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]    (nerves_hub 0.1.0) lib/nerves_hub_web/endpoint.ex:1: NervesHubWeb.Endpoint.plug_builder_call/2
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]    (nerves_hub 0.1.0) lib/nerves_hub_web/endpoint.ex:1: NervesHubWeb.Endpoint."call (overridable 3)"/2
2024-03-24T05:34:12Z app[17816e32b9e668] den [info]Last message: {:continue, :handle_connection}
```

**Comment by ConnorRigby** [comment]
likely a duplicate of https://github.com/nerves-hub/nerves_hub_web/issues/854

**Comment by joshk** [comment]
I'm wondering how best to replicate this issue.

Can you provide a bit more information on how you created the root CA pem, and the verification cert?

**Comment by ConnorRigby** [comment]
I think it is a duplicate of the above issue. I was able to import a cert more recently, so im not exactly sure what happened on this one. I'll close for now since it's covered by that other issue.
