### ISSUE TITLE
more gracious failure when attempting to delete firmware still tied to deployment

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#458]
Right now if you try to delete a firmware tied to a deployment, it just crashes.

Instead, we should handle this Changeset error more graciously and turn it into a error flash message.

While we're at it, we should probably change the error from `deployment does not exist` to something more specific to this case since it is caused _because_ the deployment _does_ exist. Message could be something like "cannot delete firmware that has any deployments"

```elixir
error] #PID<0.2606.0> running NervesHubWWWWeb.Endpoint (connection #PID<0.2573.0>, stream id 11) terminated
Server: nerves-hub.org:4000 (http)
Request: POST /products/2642/firmware/delete/2441
** (exit) an exception was raised:
    ** (RuntimeError) expected action/2 to return a Plug.Conn, all plugs must receive a connection (conn) and return a connection, got: {:error, #Ecto.Changeset<action: :delete, changes: %{}, errors: [deployments: {"does not exist", [constraint: :foreign, constraint_name: "deployments_firmware_id_fkey"]}], data: #NervesHubWebCore.Firmwares.Firmware<>, valid?: false>}
        (nerves_hub_www) lib/nerves_hub_www_web/controllers/firmware_controller.ex:1: NervesHubWWWWeb.FirmwareController.phoenix_controller_pipeline/2
        (nerves_hub_www) lib/nerves_hub_www_web/endpoint.ex:1: NervesHubWWWWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (nerves_hub_www) lib/nerves_hub_www_web/endpoint.ex:1: NervesHubWWWWeb.Endpoint.plug_builder_call/2
        (nerves_hub_www) lib/plug/debugger.ex:122: NervesHubWWWWeb.Endpoint."call (overridable 3)"/2
        (nerves_hub_www) lib/nerves_hub_www_web/endpoint.ex:1: NervesHubWWWWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:33: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /Users/jonjon/repos/nerves_hub_web/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/jonjon/repos/nerves_hub_web/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /Users/jonjon/repos/nerves_hub_web/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by chazwatkins** [comment]
I'm going to have a go at resolving this issue.
